### PR TITLE
Query builder updates, bugfixes

### LINKED ISSUE #41: neuroquery query contains all top level terms
Is this the desired behavior?

image

The NQ string contains all of the top level terms, regardless of what their toggle selector is on:

image

### LINKED ISSUE #47: broken NeuroQuery link
**Describe the bug**
the link to view results in NeuroQuery links to`https://neuroquery.org/query?text=undefined``

**To Reproduce**
1. Build a query & get results
2. Visit NeuroQuery results tab
3. Click "View these results at NeuroQuery.org"
4. See where it lands you

**Expected behavior**
User should go to `https://neuroquery.org/query?text=ConceptOne+ConceptTwo`

**Screenshots**
image

### LINKED ISSUE #48: Toggle all subtree children
Clicking a term in the query builder should toggle every child to be the same state. This was present but removed by dc40f2b572df4ed4c5382e0100df80bb91609914 when the internal data structure was refactored to a tree. Consider this the new default toggle behavior. Should also default all subtree terms to positive when a new root term is added.

### LINKED ISSUE #49: Remove NOT operator
Remove the NOT operator and red icon toggle state

### PR DESCRIPTION
**Pull request by Woozl**
closes #49 
closes #47 
closes #48 
closes #41

### CODE REVIEW

**Review by mbwatson — COMMENTED** [review]
what a productive PR -- thanks for addressing all these issues! a couple things come to mind, and both relate to that NeuroQuery link: (1) this may be a good use for a new test, and (2) i think all the selected concepts are supposed to end up in the NeuroQuery query, not only the root concepts. perhaps, we should verify this to be certain.

**Review by mbwatson — APPROVED** [review]
noting here that we have an outstanding task to confirm the NQ query is being constructed correctly, but that's a separate issue we can address later and doesn't get in the way of pushing these changes through.

**Comment by Woozl** [comment]
@mbwatson 

image

For now it just displays a warning message if there are too many terms present. I'm worried it could be more confusing though (implying something is wrong with the fetched results displayed in the table). I'm open to suggestions for improvements. Like @HowardLander said, this would only every show if the user selected a large number of terms.

**Review by mbwatson — APPROVED** [review]
:+

**Pull request merged**
