### PR TITLE
Study / Concept detail view

### LINKED ISSUE #61: Tray for terms present in paper
We will have a file that maps pmc identifiers -> array of ontology terms in that publication. We want this list of terms to show when the user clicks a publication in the results table.  A tray should pop out and show a list of concepts.

@HowardLander let me know when you've got that file ready so I can begin work on this.

### PR DESCRIPTION
**Pull request by Woozl**
https://user-images.githubusercontent.com/16181779/229171654-d7d9f21e-8cc1-43ba-aa57-b687688ebde2.mov

Work in progress but the core functionality is there. Needs to be broken up into components for readability. Should also probably have fallback/loading/error content, bc the pubmed XML data could be missing tags for certain studies.

### CODE REVIEW

**Review by mbwatson — COMMENTED** [review]
what a start! my first comment is WOW.

i think you nailed the functionality, so good job there. a few stylistic notes come to mind that may improve the already-great experience this provides.

- consider highlighting the row with study currently being viewed
- consider adding a count to the CONCEPTS accordion title, e.g., CONCEPTS - 13
- where it shows, "PubMed: 31571320" in the panel header, it looks like tabs, and i naturally wonder if tabs would make sense. maybe not, but it's worth considering the ability to "expand" multiple studies simultaneously. just a thought.

what an upgrade this will bring to this UI. keep it up!

**Comment by Woozl** [comment]
6x slowdown for illustrative purposes

Loading state:

https://user-images.githubusercontent.com/16181779/230098517-38598ec4-ca05-42f8-b9ec-1736ee48ce55.mov



Error state:

https://user-images.githubusercontent.com/16181779/230098593-2310e797-fbc3-4a41-bc9f-5208b2e13488.mov

**Comment by mbwatson** [comment]
the author modal is a nice touch

**Review by mbwatson — APPROVED** [review]
:+1:

**Pull request merged**
