### PR TITLE
Feature/publication view tabs

### PR DESCRIPTION
**Pull request by Woozl**
https://user-images.githubusercontent.com/16181779/233730432-198e60ca-6549-4e19-8837-85117d0cc736.mov

### CODE REVIEW

**Comment by mbwatson** [comment]
this is very cool! but a couple things jump out at me initially regarding functionality:

- the publication tabs' content re-fetches if i leave and return to a publication, which may impose undesirable wait time.
- it isn't obvious in the table which publications are currently being viewed, which may lead to a user clicking an already-open publication and expecting something to happen. at least it may introduce some confusion.
- that panel gets pretty cramped after opening a few publications

what thoughts do you have about these concerns, and do you have others that i've missed? i'd be happy to get together to chat these out in more detail

**Comment by Woozl** [comment]
@mbwatson  Thanks for the feedback, just saw these. Posting this vid again for the PR, which I think somewhat solves the 2nd bullet.

https://user-images.githubusercontent.com/16181779/234701525-e1aa1101-4716-4078-a6d0-321fe6a2308f.mov

- [ ] Re. bullet 1, that is definitely something that needs to be addressed before this merged. I was thinking React.memo would work since each tab panel is mounted by Mui, but it didn't work when I briefly tried it last week. There are definitely other opts here though.
- [ ]  another related point is cancelling requests if a user closes the tab/publication view before a request finishes

Re bullet 3, I was thinking this too, and considered it might be worth expanding the whole app to take up more horizontal screen space. I can imagine having the table and query builder on the left side, with the publication viewer on the right (or some other arrangement). However, I was thinking that work could be done in a different branch, since the concerns are not very related here.

**Review by mbwatson — CHANGES_REQUESTED** [review]
:+1: this is awesome!

you may not have seen it, so i'll mention it here. consider using the useLocalStorage hook that lives in the `src/hooks` directory. it's also used in the search history functionality, and it might be nice to reuse for consistency's sake.

**Comment by Woozl** [comment]
@mbwatson I did look at that, I don't remember why I didn't use it though 😅 . Now that I'm testing for the quota limit, I would have to modify that as well. Maybe it's worth unifying the API and using it in both places, but I'll go ahead and get the functionality out there first. 

I added a bunch of studies and checked the `localStorage` size. Average size of each publication is 3.8KB, so we could expect ~1300 studies to be stored (`localStorage` limit is ~5MB on all the browsers I tested, but this can vary). This seems possible to hit, especially if you're using the app for a while. To fix this we can check for the `DOMException` that happens when the limit is gone over. 

If this is the case, we can remove the oldest cached publication from the queue. However, that may not be enough if the first study in the queue is tiny and the latest is giant. My implementation is to use a recursive function which deques as many times as necessary to fit the new study in. Because this has the potential to recurse forever, I put a limit on this: `MAX_ATTEMPTS`, which I hardcoded to 25. There may be a better way to do this however.

To test, I added a large key ~1MB so only 5 publications fit in storage
image

Clicking on several studies not in the queue, we can see the old ones dequed and new ones added in

https://github.com/NeuroBridge/Search-Portal/assets/16181779/e1518154-39c2-4ab0-8392-029c85466245

**Pull request merged**
