### PR TITLE
Feature/health check

### LINKED ISSUE #59: Health Check
**Is your feature request related to a problem? Please describe.**
Users don't know if a service (NQ or the NB API) until they actually press the "Search" button. to enhance UX, we should consider alerting users with a "data source health check" upon loading the application. 

**Describe the solution you'd like**
SchizConnect is a comparable application that does this; here is a screenshot for inspiration:

schizconnect-health-check

**Describe alternatives you've considered**
We have not considered this before.

**Additional context**
The NB-to-NQ transformer API already has such an endpoint used by K8s, which we could also use here. See [here](https://github.com/NeuroBridge/neuro-query-dense-vectors/blob/main/neuroQuerySearchAppSapBert.py#L49).

### PR DESCRIPTION
**Pull request by Woozl**
Closes #59 

---

https://user-images.githubusercontent.com/16181779/226390483-1b9db005-08fb-4640-88f1-4632338ede59.mov

---

I'm doing dummy queries as a for NB and NQ to check that the service is up, but we may want to have a dedicated `/healthz` endpoint like the NB-NQ translator for this purpose:

```ts
const STATUS_URLS = [
  {
    name: "NeuroQuery",
    url: "https://neurobridges.renci.org:13374/query?searchTerms=abstinence",
    method: "GET",
  },
  {
    name: "NeuroBridge",
    url: "https://neurobridges-ml.renci.org/nb_translator",
    method: "POST",
    body: {
      query: {
        expression: {
          OR: ["Abstinent"],
        },
        max_res: 100,
      },
    },
  },
  {
    name: "NB-NQ Translator",
    url: "https://neurobridges.apps.renci.org/healthz",
    method: "GET",
  },
];
```

---

 Error state:
image

### CODE REVIEW

**Comment by Woozl** [comment]
@HowardLander could we get a [`/healthz`](https://github.com/NeuroBridge/neuro-query-dense-vectors/blob/3199bf08818cdce4619fb9965950bacd38a59b61/neuroQuerySearchAppSapBert.py#L49-L51) endpoint on these services for this feature?

NB: https://github.com/NeuroBridge/Backend_service
NQ: https://github.com/NeuroBridge/neuroquery_webapp

**Comment by HowardLander** [comment]
We are getting ready to move the backend service to sterling/kubernetes, at which point we will definitely add the health check.

Are we really using the neuroquery_webapp?  Where is it running?  I thought we were using the /neuroquery endpoint from https://github.com/NeuroBridge/neuro-query-dense-vectors/blob/main/neuroQuerySearchAppSapBert.py which is running on sterling and does have the health check

Howard
________________________________

**Comment by Woozl** [comment]
I'm assuming it's neuroquery_webapp still, maybe it didn't get moved over:

`const NQ_API_URL = 'https://neurobridges.renci.org:13374/query'`

**Comment by HowardLander** [comment]
Try the sterling version and make sure it works,  Here's an example query:

https://neurobridges.apps.renci.org/neuroquery?searchTerms=schizophrenia
________________________________

**Comment by Woozl** [comment]
Yep, that works, guess it just never got changed. I guess it doesn't make sense to have both NQ and the NB-NQ translator in the status gui now, since they're on the same service 😅

**Comment by HowardLander** [comment]
Well, stuff happens as they say!

There is still an issue in that the NeuroQuery itself could be down.  I had a quick look at their code and I'm not sure there is any way to check.  I'm also not sure how the code of theirs that we are calling works:  maybe it doesn't rely on a service at their end.
________________________________

**Comment by HowardLander** [comment]
It looks like the NeuroQuery code we call is downloading from

https://osf.io/598tj/download

So as long as that works we are safe.  Seems like their code should check to see if the file it wants is already downloaded, but I didn't see any sign it's doing so.
________________________________

**Review by mbwatson — COMMENTED** [review]
this is great; what a good implementation! i love the look of this and how seamlessly it fits in.

i do experience the app crashing if i block the internet connection, though.

also, i wonder if Promise.all() is more appropriate for these requests?

**Comment by Woozl** [comment]
> i do experience the app crashing if i block the internet connection, though.

Good catch! I was missing `catch` on the promises.

> also, i wonder if Promise.all() is more appropriate for these requests?

Yeah at first I tried it with `Promise.allSettled`, but that constructs a new promise that resolves when *all* of the services respond. I wanted the state to be set independently so the UI can update each service as it responds. Do you know of a way to do that more cleanly?

**Comment by Woozl** [comment]
> It looks like the NeuroQuery code we call is downloading from
>
> https://osf.io/598tj/download
>
> So as long as that works we are safe.  Seems like their code should check to see if the file it wants is already downloaded, but I didn't see any sign it's doing so.

I think that check would make the most sense in the backend. This GUI only turns the service green if the server responds with a 200 status. Maybe the `/neuroquery` endpoint could return a 500 status if there is an issue fetching the NQ model file.

**Comment by Woozl** [comment]
I'm going to fix the NQ url mismatch in #58. Merging this as it seems to working well now.

**Pull request merged**
